### ISSUE TITLE
cmd+k r shortcut still types "r" on the screen

### ISSUE THREAD

**Issue by wolverdude** [robenkleene/run-in-atom#5]
The keyboard shortcut `cmd+k r` works, but it still types the `"r"` on my screen so that it messes up the script before running it. As a result I always get something like:

```
Run in Atom Error: ReferenceError: r is not defined
```

This makes the keyboard shortcut unusable. Please either fix or select a single-part keyboard shortcut (or even better, make the shortcut changeable from the package configuration view).

_(I'm using Mac OSX Yosemite with Atom 1.3.2 and `run-in-atom` 1.0.3)_

**Comment by robenkleene** [comment]
Hi wolverdude, thanks for the report. I just pushed an update to change the keyboard shortcut to `alt-cmd-r`.

(And just FYI, Atom already has a built-in mechanism for overriding key bindings by [editing the `keymap.cson`](https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings).)

Cheers,
-Roben

**Comment by wolverdude** [comment]
All works smoothly now. Thanks for the quick fix, you're awesome!

I should probably look into keymaps configuration considering that the first language I learned was _AutoHotkey_.

**Comment by darkmou5e** [comment]
Hi! I had same problem with **cmd-k r** on a stable atom build. But on dev build 1.4.0-dev-80faae4 it works fine. Looks like it is an atom bug.
